# ==> Install nfs packages
- name: Install nfs-utils
  yum: name=nfs-utils state=latest

# ==> Create mountable directory
- name: Create a mountable directory
  file: state=directory path={{ nfs_base_external }} owner={{ oracle_user_id }} group={{ oracle_group_id }}

# ==> Mount volume
- name: Mount share
  mount: 
    src: "{{ nfs_external }}"
    path: '{{ nfs_base_external }}'
    opts: rw,sync,hard,intr
    # opts: rw,bg,vers=3,hard,rsize=32767,wsize=32767,timeo=600
    state: mounted
    fstype: nfs